"""empty message

Revision ID: 0b06829a12f6
Revises: b5ffa11544b2
Create Date: 2025-10-14 16:48:31.011507

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b06829a12f6"
down_revision: str | None = "b5ffa11544b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("published", sa.Date(), nullable=True))
    op.drop_column("posts", "published_2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("published_2", sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column("posts", "published")
    # ### end Alembic commands ###
