"""empty message

Revision ID: 622938617020
Revises: fb7117be9ea4
Create Date: 2025-10-03 10:54:42.385205

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "622938617020"
down_revision: str | None = "fb7117be9ea4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "content", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True)
    op.alter_column("posts", "content2", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "content2", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True)
    op.alter_column("posts", "content", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=True)
    # ### end Alembic commands ###
