"""empty message

Revision ID: 683b94ee3704
Revises: f3746f8ae7cb
Create Date: 2025-10-07 20:09:58.328004

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# from typing import Union


# revision identifiers, used by Alembic.
revision: str = "683b94ee3704"
down_revision: str | None = "f3746f8ae7cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posttags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posttags_id"), "posttags", ["id"], unique=False)
    op.drop_constraint("tags_post_id_fkey", "tags", type_="foreignkey")
    op.drop_column("tags", "post_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("post_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key("tags_post_id_fkey", "tags", "posts", ["post_id"], ["id"])
    op.drop_index(op.f("ix_posttags_id"), table_name="posttags")
    op.drop_table("posttags")
    # ### end Alembic commands ###
