"""empty message

Revision ID: 95a6fbb2a83f
Revises: 59758f719fa7
Create Date: 2025-10-18 22:59:34.265726

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95a6fbb2a83f"
down_revision: str | None = "59758f719fa7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("username", sa.String(), nullable=True))
    op.add_column("sites", sa.Column("password", sa.String(), nullable=True))
    op.drop_column("sites", "access_token")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("sites", "password")
    op.drop_column("sites", "username")
    # ### end Alembic commands ###
