"""empty message

Revision ID: aa490a456894
Revises: 95a6fbb2a83f
Create Date: 2025-10-18 23:42:21.420446

"""
from typing import Union

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa490a456894"
down_revision: str | None = "95a6fbb2a83f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("siteposts", sa.Column("sended", sa.Boolean(), server_default="false", nullable=True))
    op.drop_column("siteposts", "send")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "siteposts",
        sa.Column("send", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=True),
    )
    op.drop_column("siteposts", "sended")
    # ### end Alembic commands ###
