"""empty message

Revision ID: b5ffa11544b2
Revises: e40c7283d54f
Create Date: 2025-10-14 16:48:19.922794

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5ffa11544b2"
down_revision: str | None = "e40c7283d54f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "published")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("published", postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
