"""empty message

Revision ID: d5bac1fdfbdb
Revises: aa490a456894
Create Date: 2025-10-30 15:57:47.124176

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5bac1fdfbdb"
down_revision: str | None = "aa490a456894"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sites", sa.Column("max_connections_limit", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sites", "max_connections_limit")
    # ### end Alembic commands ###
