"""empty message

Revision ID: e40c7283d54f
Revises: 683b94ee3704
Create Date: 2025-10-14 16:48:05.848134

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e40c7283d54f"
down_revision: str | None = "683b94ee3704"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("published_2", sa.Date(), nullable=True))
    op.create_unique_constraint(None, "tags", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="unique")
    op.drop_column("posts", "published_2")
    # ### end Alembic commands ###
