"""empty message

Revision ID: fb7117be9ea4
Revises: d6c12961eade
Create Date: 2025-10-03 00:22:04.423096

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb7117be9ea4"
down_revision: str | None = "d6c12961eade"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("name", sa.String(), nullable=True))
    op.add_column("tags", sa.Column("slug", sa.String(), nullable=True))
    op.drop_column("tags", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tags", sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column("tags", "slug")
    op.drop_column("tags", "name")
    # ### end Alembic commands ###
